version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: healthcare-postgres-prod
    environment:
      POSTGRES_USER: myexpo
      POSTGRES_PASSWORD: myexpo123
      POSTGRES_DB: healthcare_prod
    volumes:
      - healthcare_postgres_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myexpo"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: healthcare-redis-prod
    volumes:
      - healthcare_redis_prod:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Main Application
  app:
    image: healthcare-alerts/app
    container_name: healthcare-app-prod
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://myexpo:myexpo123@postgres:5432/healthcare_prod
      REDIS_URL: redis://redis:6379
      BETTER_AUTH_SECRET: 21HK9bF2lrdAGZfrBVfA9IcAYiBn93JKUfyTVSnWgSM=
      BETTER_AUTH_URL: http://localhost:3000
      EXPO_PUBLIC_API_URL: http://localhost:3000
      EXPO_PUBLIC_WS_URL: ws://localhost:3002
      EXPO_PUBLIC_POSTHOG_ENABLED: false
      EXPO_PUBLIC_ENVIRONMENT: production
      EXPO_PUBLIC_DEBUG_MODE: false
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs

volumes:
  healthcare_postgres_prod:
  healthcare_redis_prod:

networks:
  default:
    name: healthcare-network-prod