#!/usr/bin/env bun
import { readdir, readFile, writeFile } from 'fs/promises';
import { join } from 'path';

const iconMap = {
  // Common icons
  Search: 'magnifyingglass',
  Filter: 'line.3.horizontal.decrease.circle',
  Download: 'arrow.down.circle.fill',
  Calendar: 'calendar',
  Clock: 'clock.fill',
  CheckCircle: 'checkmark.circle.fill',
  XCircle: 'xmark.circle.fill',
  AlertCircle: 'exclamationmark.circle.fill',
  TrendingUp: 'arrow.up.right.circle.fill',
  FileText: 'doc.text.fill',
  History: 'clock.arrow.circlepath',
  UserPlus: 'person.fill.badge.plus',
  MoreVertical: 'ellipsis.vertical',
  ChevronDown: 'chevron.down',
  ChevronUp: 'chevron.up',
  ChevronRight: 'chevron.right',
  ChevronLeft: 'chevron.left',
  Plus: 'plus',
  Minus: 'minus',
  Edit: 'pencil',
  Trash: 'trash.fill',
  Eye: 'eye.fill',
  EyeOff: 'eye.slash.fill',
  Settings: 'gearshape.fill',
  Users: 'person.2.fill',
  User: 'person.fill',
  Shield: 'shield.fill',
  Bell: 'bell.fill',
  Heart: 'heart.fill',
  Star: 'star.fill',
  ArrowUp: 'arrow.up',
  ArrowDown: 'arrow.down',
  ArrowRight: 'arrow.right',
  ArrowLeft: 'arrow.left',
  Check: 'checkmark',
  X: 'xmark',
  Info: 'info.circle.fill',
  Activity: 'waveform.path.ecg',
  BarChart: 'chart.bar.fill',
  PieChart: 'chart.pie.fill',
  TrendingDown: 'arrow.down.right.circle.fill',
  Briefcase: 'briefcase.fill',
  Package: 'shippingbox.fill',
  Layers: 'square.3.layers.3d',
  Activity: 'waveform.path.ecg',
  Monitor: 'display',
  Smartphone: 'iphone',
  Mail: 'envelope.fill',
  MessageSquare: 'message.fill',
  Phone: 'phone.fill',
  Camera: 'camera.fill',
  Image: 'photo.fill',
  Video: 'video.fill',
  Mic: 'mic.fill',
  Volume: 'speaker.wave.3.fill',
  Wifi: 'wifi',
  Battery: 'battery.100',
  Bluetooth: 'bluetooth',
  Database: 'externaldrive.fill',
  Server: 'server.rack',
  Cloud: 'cloud.fill',
  Lock: 'lock.fill',
  Unlock: 'lock.open.fill',
  Key: 'key.fill',
  CreditCard: 'creditcard.fill',
  DollarSign: 'dollarsign.circle.fill',
  Gift: 'gift.fill',
  Award: 'rosette',
  Flag: 'flag.fill',
  MapPin: 'mappin.circle.fill',
  Navigation: 'location.north.fill',
  Compass: 'safari.fill',
  Globe: 'globe',
  Home: 'house.fill',
  Building: 'building.2.fill',
  Archive: 'archivebox.fill',
  Folder: 'folder.fill',
  File: 'doc.fill',
  Clipboard: 'clipboard.fill',
  Copy: 'doc.on.doc.fill',
  Printer: 'printer.fill',
  Share: 'square.and.arrow.up',
  Link: 'link',
  Paperclip: 'paperclip',
  Tag: 'tag.fill',
  Bookmark: 'bookmark.fill',
  Hash: 'number',
  AtSign: 'at',
  Percent: 'percent',
  Code: 'chevron.left.forwardslash.chevron.right',
  Terminal: 'terminal.fill',
  Cpu: 'cpu',
  Zap: 'bolt.fill',
  Anchor: 'anchor',
  Send: 'paperplane.fill',
  Inbox: 'tray.fill',
  Package2: 'shippingbox.fill',
  LayoutGrid: 'square.grid.2x2.fill',
  Layers2: 'square.3.layers.3d',
  GitBranch: 'arrow.triangle.branch',
  Shuffle: 'shuffle',
  RefreshCw: 'arrow.2.circlepath',
  RotateCw: 'arrow.clockwise',
  Save: 'square.and.arrow.down.fill',
  Upload: 'square.and.arrow.up.fill',
  ZoomIn: 'plus.magnifyingglass',
  ZoomOut: 'minus.magnifyingglass',
  LogOut: 'rectangle.portrait.and.arrow.right',
  LogIn: 'rectangle.portrait.and.arrow.left',
  CircleAlert: 'exclamationmark.circle.fill',
  CircleUser: 'person.circle.fill',
  Stethoscope: 'stethoscope',
  Siren: 'light.beacon.max.fill',
  BellRing: 'bell.badge.fill',
  CalendarDays: 'calendar',
  ClipboardList: 'list.clipboard.fill',
  FileCheck: 'checkmark.rectangle.fill',
  UserCheck: 'person.fill.checkmark',
  UsersRound: 'person.3.fill',
  Gauge: 'gauge',
  HeartPulse: 'heart.text.square.fill',
  Pill: 'pills.fill',
  Syringe: 'syringe.fill',
  TestTube: 'testtube.2',
  Thermometer: 'thermometer',
  BedDouble: 'bed.double.fill',
  Building2: 'building.2.fill',
  Timer: 'timer',
  MoreHorizontal: 'ellipsis',
  Menu: 'line.3.horizontal',
  Grid: 'square.grid.3x3.fill',
  List: 'list.bullet',
  Columns: 'rectangle.split.3x1.fill',
  Maximize: 'arrow.up.left.and.arrow.down.right',
  Minimize: 'arrow.down.right.and.arrow.up.left',
  Move: 'arrow.up.and.down.and.arrow.left.and.right',
  Play: 'play.fill',
  Pause: 'pause.fill',
  SkipForward: 'forward.fill',
  SkipBack: 'backward.fill',
  FastForward: 'forward.end.fill',
  Rewind: 'backward.end.fill',
  Volume2: 'speaker.wave.2.fill',
  VolumeX: 'speaker.slash.fill',
  Music: 'music.note',
  Radio: 'radio.fill',
  Tv: 'tv.fill',
  Laptop: 'laptopcomputer',
  Watch: 'applewatch',
  Moon: 'moon.fill',
  Sun: 'sun.max.fill',
  CloudRain: 'cloud.rain.fill',
  CloudSnow: 'cloud.snow.fill',
  Wind: 'wind',
  Droplet: 'drop.fill',
  Flame: 'flame.fill',
  Coffee: 'cup.and.saucer.fill',
  Pizza: 'fork.knife',
  Apple: 'applelogo',
  Car: 'car.fill',
  Bike: 'bicycle',
  Train: 'tram.fill',
  Plane: 'airplane',
  Ship: 'ferry.fill',
  Bus: 'bus.fill',
  Truck: 'truck.box.fill',
  Fuel: 'fuelpump.fill',
  Parking: 'parkingsign.circle.fill',
  CircleCheck: 'checkmark.circle.fill',
  CircleX: 'xmark.circle.fill',
  CirclePlus: 'plus.circle.fill',
  CircleMinus: 'minus.circle.fill',
  Square: 'square.fill',
  Circle: 'circle.fill',
  Triangle: 'triangle.fill',
  Heart: 'heart.fill',
  Hexagon: 'hexagon.fill',
  Octagon: 'octagon.fill',
  SquareCheck: 'checkmark.square.fill',
  SquareX: 'xmark.square.fill',
  SquarePlus: 'plus.square.fill',
  SquareMinus: 'minus.square.fill',
  ArrowUpCircle: 'arrow.up.circle.fill',
  ArrowDownCircle: 'arrow.down.circle.fill',
  ArrowRightCircle: 'arrow.right.circle.fill',
  ArrowLeftCircle: 'arrow.left.circle.fill',
  Loader: 'arrow.2.circlepath',
  Loader2: 'arrow.2.circlepath',
  Settings2: 'gearshape.2.fill',
  Eye2: 'eye.fill',
  Calendar2: 'calendar',
  Trash2: 'trash.fill',
  Edit2: 'pencil',
  Edit3: 'pencil.circle.fill',
  Bookmark2: 'bookmark.fill',
  Bell2: 'bell.fill',
  BellOff: 'bell.slash.fill',
  MessageCircle: 'message.circle.fill',
  MessagesSquare: 'bubble.left.and.bubble.right.fill',
  PlusCircle: 'plus.circle.fill',
  MinusCircle: 'minus.circle.fill',
  Upload2: 'square.and.arrow.up.fill',
  Download2: 'square.and.arrow.down.fill',
  Heart2: 'heart.fill',
  Star2: 'star.fill',
  UserCircle: 'person.circle.fill',
  UserCircle2: 'person.circle.fill',
  MapPin2: 'mappin.circle.fill',
  ShoppingCart: 'cart.fill',
  ShoppingBag: 'bag.fill',
  Receipt: 'receipt',
  Wallet: 'wallet.pass.fill',
  Crown: 'crown.fill',
  Medal: 'medal.fill',
  Trophy: 'trophy.fill',
  Target: 'target',
  Crosshair: 'scope',
  Navigation2: 'location.north.fill',
  Map: 'map.fill',
  Filter2: 'line.3.horizontal.decrease.circle',
  SortAsc: 'arrow.up.arrow.down',
  SortDesc: 'arrow.down.arrow.up',
  AlignLeft: 'text.alignleft',
  AlignCenter: 'text.aligncenter',
  AlignRight: 'text.alignright',
  AlignJustify: 'text.justify',
  Bold: 'bold',
  Italic: 'italic',
  Underline: 'underline',
  Strikethrough: 'strikethrough',
  Type: 'textformat',
  FileText2: 'doc.text.fill',
  FilePlus: 'doc.fill.badge.plus',
  FileMinus: 'doc.fill.badge.minus',
  FileCheck2: 'checkmark.rectangle.fill',
  FileX: 'xmark.rectangle.fill',
  FolderOpen: 'folder.fill',
  FolderPlus: 'folder.fill.badge.plus',
  FolderMinus: 'folder.fill.badge.minus',
  FolderCheck: 'folder.fill.badge.checkmark',
  FolderX: 'folder.fill.badge.xmark',
  Archive2: 'archivebox.fill',
  Inbox2: 'tray.fill',
  Send2: 'paperplane.fill',
  Reply: 'arrowshape.turn.up.left.fill',
  ReplyAll: 'arrowshape.turn.up.left.2.fill',
  Forward: 'arrowshape.turn.up.right.fill',
  Link2: 'link',
  Unlink: 'link.badge.plus',
  ExternalLink: 'arrow.up.forward.square.fill',
  Anchor2: 'anchor',
  Hash2: 'number',
  AtSign2: 'at',
  Copyright: 'c.circle.fill',
  Registered: 'r.circle.fill',
  Trademark: 'tm.circle.fill',
  DollarSign2: 'dollarsign.circle.fill',
  Euro: 'eurosign.circle.fill',
  Pound: 'sterlingsign.circle.fill',
  Yen: 'yensign.circle.fill',
  Bitcoin: 'bitcoinsign.circle.fill',
  CreditCard2: 'creditcard.fill',
  ShieldCheck: 'checkmark.shield.fill',
  ShieldAlert: 'exclamationmark.shield.fill',
  ShieldX: 'xmark.shield.fill',
  Lock2: 'lock.fill',
  Unlock2: 'lock.open.fill',
  Key2: 'key.fill',
  Fingerprint: 'touchid',
  Scan: 'qrcode.viewfinder',
  ScanLine: 'barcode.viewfinder',
  QrCode: 'qrcode',
  Barcode: 'barcode',
  Cpu2: 'cpu',
  HardDrive: 'internaldrive.fill',
  Database2: 'externaldrive.fill',
  Server2: 'server.rack',
  Wifi2: 'wifi',
  WifiOff: 'wifi.slash',
  Bluetooth2: 'bluetooth',
  Cast: 'airplayaudio',
  Airplay: 'airplayvideo',
  Smartphone2: 'iphone',
  Tablet: 'ipad',
  Laptop2: 'laptopcomputer',
  Monitor2: 'display',
  Tv2: 'tv.fill',
  Speaker: 'hifispeaker.fill',
  Headphones: 'headphones',
  Gamepad: 'gamecontroller.fill',
  Gamepad2: 'gamecontroller.fill',
  Watch2: 'applewatch',
  Camera2: 'camera.fill',
  Video2: 'video.fill',
  Image2: 'photo.fill',
  Film: 'film.fill',
  Radio2: 'radio.fill',
  Mic2: 'mic.fill',
  MicOff: 'mic.slash.fill',
  Volume3: 'speaker.wave.3.fill',
  VolumeX2: 'speaker.slash.fill',
  Music2: 'music.note',
  Music3: 'music.note',
  Music4: 'music.note',
  Disc: 'opticaldisc.fill',
  Disc2: 'opticaldisc.fill',
  Album: 'rectangle.stack.fill',
  Ticket: 'ticket.fill',
  Tag2: 'tag.fill',
  Tags: 'tag.fill',
  Bookmark3: 'bookmark.fill',
  Award2: 'rosette',
  Medal2: 'medal.fill',
  Trophy2: 'trophy.fill',
  Crown2: 'crown.fill',
  Gift2: 'gift.fill',
  Package3: 'shippingbox.fill',
  Truck2: 'truck.box.fill',
  Bike2: 'bicycle',
  Car2: 'car.fill',
  Bus2: 'bus.fill',
  Train2: 'tram.fill',
  Plane2: 'airplane',
  Ship2: 'ferry.fill',
  Anchor3: 'anchor',
  Rocket: 'airplane.departure',
  Globe2: 'globe',
  Compass2: 'safari.fill',
  Map2: 'map.fill',
  MapPin3: 'mappin.circle.fill',
  Navigation3: 'location.north.fill',
  Flag2: 'flag.fill',
  Home2: 'house.fill',
  Building3: 'building.2.fill',
  Store: 'storefront.fill',
  Hotel: 'bed.double.fill',
  School: 'graduationcap.fill',
  Hospital: 'cross.case.fill',
  Church: 'building.columns.fill',
  Landmark: 'building.columns.circle.fill',
  Trees: 'tree.fill',
  Mountain: 'mountain.2.fill',
  Sunrise: 'sunrise.fill',
  Sunset: 'sunset.fill',
  CloudSun: 'cloud.sun.fill',
  CloudMoon: 'cloud.moon.fill',
  CloudLightning: 'cloud.bolt.fill',
  CloudDrizzle: 'cloud.drizzle.fill',
  CloudFog: 'cloud.fog.fill',
  Snowflake: 'snowflake',
  Thermometer2: 'thermometer',
  Droplets: 'drop.fill',
  Waves: 'waveform',
  Zap2: 'bolt.fill',
  Flame2: 'flame.fill',
  Fan: 'fanblades.fill',
  Leaf: 'leaf.fill',
  Flower: 'camera.macro',
  Cherry: 'leaf.fill',
  Pizza2: 'fork.knife',
  Coffee2: 'cup.and.saucer.fill',
  Wine: 'wineglass.fill',
  Beer: 'mug.fill',
  Milk: 'drop.fill',
  Utensils: 'fork.knife',
  Apple2: 'applelogo',
  Carrot: 'carrot.fill',
  Candy: 'birthday.cake.fill',
  Cookie: 'circle.hexagongrid.fill',
  IceCream: 'cone.fill',
  Soup: 'cup.and.saucer.fill',
  Fish: 'fish.fill',
  EggFried: 'circle.fill',
  Popcorn: 'popcorn.fill',
  Sandwich: 'rectangle.fill.on.rectangle.fill',
  Salad: 'leaf.fill',
  Cake: 'birthday.cake.fill',
  Clock2: 'clock.fill',
  Clock3: 'clock.fill',
  Clock4: 'clock.fill',
  Clock5: 'clock.fill',
  Clock6: 'clock.fill',
  Clock7: 'clock.fill',
  Clock8: 'clock.fill',
  Clock9: 'clock.fill',
  Clock10: 'clock.fill',
  Clock11: 'clock.fill',
  Clock12: 'clock.fill',
  Stopwatch: 'stopwatch.fill',
  Timer2: 'timer',
  AlarmClock: 'alarm.fill',
  AlarmClockOff: 'alarm.fill',
  CalendarClock: 'calendar.badge.clock',
  CalendarCheck: 'calendar.badge.checkmark',
  CalendarCheck2: 'calendar.badge.checkmark',
  CalendarX: 'calendar.badge.exclamationmark',
  CalendarX2: 'calendar.badge.exclamationmark',
  CalendarPlus: 'calendar.badge.plus',
  CalendarMinus: 'calendar.badge.minus',
  CalendarHeart: 'heart.text.square.fill',
  CalendarSearch: 'magnifyingglass',
  Undo: 'arrow.uturn.backward',
  Undo2: 'arrow.uturn.backward',
  Redo: 'arrow.uturn.forward',
  Redo2: 'arrow.uturn.forward',
  History2: 'clock.arrow.circlepath',
  RotateCcw: 'arrow.counterclockwise',
  RotateCw2: 'arrow.clockwise',
  RefreshCcw: 'arrow.counterclockwise',
  RefreshCw2: 'arrow.2.circlepath',
  Repeat: 'repeat',
  Repeat2: 'repeat',
  Share2: 'square.and.arrow.up',
  Share3: 'square.and.arrow.up',
  Import: 'square.and.arrow.down',
  Export: 'square.and.arrow.up',
  Printer2: 'printer.fill',
  Scan2: 'qrcode.viewfinder',
  Copy2: 'doc.on.doc.fill',
  Copy3: 'doc.on.doc.fill',
  Scissors: 'scissors',
  Clipboard2: 'clipboard.fill',
  ClipboardCheck: 'checkmark.rectangle.fill',
  ClipboardX: 'xmark.rectangle.fill',
  ClipboardCopy: 'doc.on.clipboard.fill',
  ClipboardPaste: 'doc.on.clipboard.fill',
  ClipboardType: 'doc.on.clipboard.fill',
};

async function processFile(filePath: string) {
  try {
    let content = await readFile(filePath, 'utf-8');
    
    // Check if file imports from lucide-react-native
    if (!content.includes('lucide-react-native')) {
      return false;
    }
    
// TODO: Replace with structured logging - /* console.log(`Processing ${filePath}...`) */;
    
    // Replace the import statement
    content = content.replace(
      /import\s*\{[^}]+\}\s*from\s*['"]lucide-react-native['"];?/g,
      "import { Symbol } from '@/components/universal/Symbols';"
    );
    
    // Replace each icon usage
    for (const [oldIcon, newIcon] of Object.entries(iconMap)) {
      // Replace <IconName size={X} className="..." />
      const regex1 = new RegExp(`<${oldIcon}\\s+size={(\\d+)}\\s*(?:className="[^"]*")?\\s*/?>`, 'g');
      content = content.replace(regex1, (match, size) => {
        return `<Symbol name="${newIcon}" size={${size}} color={theme.foreground} />`;
      });
      
      // Replace <IconName size={X} color="..." />
      const regex2 = new RegExp(`<${oldIcon}\\s+size={(\\d+)}\\s+color="([^"]*)"\\s*/?>`, 'g');
      content = content.replace(regex2, (match, size, color) => {
        return `<Symbol name="${newIcon}" size={${size}} color="${color}" />`;
      });
      
      // Replace <IconName className="..." size={X} />
      const regex3 = new RegExp(`<${oldIcon}\\s+className="[^"]*"\\s+size={(\\d+)}\\s*/?>`, 'g');
      content = content.replace(regex3, (match, size) => {
        return `<Symbol name="${newIcon}" size={${size}} color={theme.foreground} />`;
      });
      
      // Replace simple <IconName /> usage
      const regex4 = new RegExp(`<${oldIcon}\\s*/?>`, 'g');
      content = content.replace(regex4, `<Symbol name="${newIcon}" size={24} color={theme.foreground} />`);
    }
    
    // Fix className-based color references
    content = content.replace(/className="text-green-500"/g, 'color={theme.emerald}');
    content = content.replace(/className="text-blue-500"/g, 'color={theme.blue}');
    content = content.replace(/className="text-yellow-500"/g, 'color={theme.yellow}');
    content = content.replace(/className="text-red-500"/g, 'color={theme.destructive}');
    content = content.replace(/className="text-gray-500"/g, 'color={theme.muted}');
    content = content.replace(/className="text-muted-foreground"/g, 'color={theme.mutedForeground}');
    
    await writeFile(filePath, content, 'utf-8');
// TODO: Replace with structured logging - /* console.log(`✓ Fixed ${filePath}`) */;
    return true;
  } catch (error) {
    console.error(`Error processing ${filePath}:`, error);
    return false;
  }
}

async function processDirectory(dir: string) {
  const entries = await readdir(dir, { withFileTypes: true });
  let filesProcessed = 0;
  
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    
    if (entry.isDirectory()) {
      // Skip node_modules and hidden directories
      if (!entry.name.startsWith('.') && entry.name !== 'node_modules') {
        filesProcessed += await processDirectory(fullPath);
      }
    } else if (entry.isFile() && (entry.name.endsWith('.tsx') || entry.name.endsWith('.ts'))) {
      if (await processFile(fullPath)) {
        filesProcessed++;
      }
    }
  }
  
  return filesProcessed;
}

// Main execution
const targetDirs = ['app', 'components'];

async function main() {
// TODO: Replace with structured logging - /* console.log('Fixing lucide-react-native imports...\n') */;
  
  let totalFixed = 0;
  for (const dir of targetDirs) {
    const fixed = await processDirectory(dir);
    totalFixed += fixed;
  }
  
// TODO: Replace with structured logging - /* console.log(`\n✅ Fixed ${totalFixed} files`) */;
}

main().catch(console.error);